### ISSUE TITLE
Check that we do not exceed feature threshold on tiles

### ISSUE THREAD

**Issue by MortenHofft** [gbif/maps#53]
When doing geo aggregations there is a default threshold/size. The default is 10.000 results
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-geohashgrid-aggregation.html

So if we have a fine precision on our geohash size and that return more than 10K buckets for a tile, then we loose data on the map. 
I wonder if we should add logging to ensure that the threshold isn't met. And if so we could consider adjusting the precision for that zoom level?

I believe I met that threshold and noticed data disappearing on the maps when I did the initial testing on the javascript tile server.
It should also be possible to calculate what a max precision can be for a tile - no more than 10K (or whatever we change the `size`to be) possible geohashes per tile including the tile buffer.

**Comment by MortenHofft** [comment]
This looks suspicious to me. Why are there no records west of South America? Based on how close some of the other points are to each other we have a detailed precision, but yet there are no records in large parts of the ocean. records that are there when you zoom in.

https://api.gbif.org/v2/map/occurrence/adhoc/0/0/0@2x.png?style=scaled.circles&mode=GEO_CENTROID&srs=EPSG%3A3857&squareSize=256
![0@2x](https://user-images.githubusercontent.com/6759267/152764776-5f253af5-169d-4043-98c3-76c38193b051.png)

It is more apparent in the mercator version since it is one tile, but it is also visible in the wgs84 version
zoom level 0
<img width="742" alt="Screenshot 2022-02-07 at 10 51 57" src="https://user-images.githubusercontent.com/6759267/152765058-8f7da709-e39b-444d-8f3e-1b0637dfa953.png">
zoom level 1
<img width="736" alt="Screenshot 2022-02-07 at 10 52 02" src="https://user-images.githubusercontent.com/6759267/152765092-be47ba7d-1beb-4e73-a7f8-de48c50352a9.png">

**Comment by MortenHofft** [comment]
As far as I can see we use precision 3 for zoom level 0
https://github.com/gbif/occurrence/blob/master/occurrence-heatmaps/src/main/java/org/gbif/occurrence/search/heatmap/es/EsHeatmapRequestBuilder.java#L41

Using this library that means
```
var Geohash = require("latlon-geohash@1.1.0");
var g = Geohash.encode(0, 0, 3); //s00
Geohash.bounds(g) // {sw: Object {lat: 0, lon: 0}, ne: Object {lat: 1.40625, lon: 1.40625}}
```

So a lat/lon size of 1.40625. ´360/1.40625 = 256` and `180/1.40625 = 128`. So I suppose that means that we can expect up to `256*128=32.768` buckets for zoom level 0 with this precision?

**Comment by timrobertson100** [comment]
@marcos-lg - I recall you know a lot about bucket size limits for maps. Can you please look if we can simply increase the bucket count?

Zoom out on this map, and then look at the atlantic - lots of missing data
https://react-components.gbif.org/?path=/story/search-occurrencesearch--example

**Comment by MattBlissett** [comment]
You are correct, there were missing points at zoom 0.

I've deployed a fix to UAT.

**Comment by MortenHofft** [comment]
I see the fix is to increase bucket size and reduce details on zoom level 0. But this could still fail on other tiles (e.g. zoom level 7 in a very dense area). Would it make sense to add some monitoring/logging so we know when/if this happens again?
